# subdir and objects in current dir
SUBDIRS	= fan get_data iniparser  key scan_com serial spi version
OBJECTS	= main.o


all:subdirs ${OBJECTS}

	
clean:cleansubdirs
	rm -f ${OBJECTS}
	
include ${MAKEINCLUDE}
