/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zjpavt_client_nativemethod_JnIMethod */

#ifndef _Included_com_zjpavt_client_nativemethod_JnIMethod
#define _Included_com_zjpavt_client_nativemethod_JnIMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zjpavt_client_nativemethod_JnIMethod
 * Method:    printTextNative
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zjpavt_client_nativemethod_JnIMethod_printTextNative
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_zjpavt_client_nativemethod_JnIMethod
 * Method:    printTextWithPosNative
 * Signature: (IIC)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zjpavt_client_nativemethod_JnIMethod_printTextWithPosNative
  (JNIEnv *, jclass, jint, jint, jchar);

/*
 * Class:     com_zjpavt_client_nativemethod_JnIMethod
 * Method:    changeAllLedStatusNative
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zjpavt_client_nativemethod_JnIMethod_changeAllLedStatusNative
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_zjpavt_client_nativemethod_JnIMethod
 * Method:    changeLedStatusNative
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zjpavt_client_nativemethod_JnIMethod_changeLedStatusNative
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_zjpavt_client_nativemethod_JnIMethod
 * Method:    changeAllChannelStatusNative
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zjpavt_client_nativemethod_JnIMethod_changeAllChannelStatusNative
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_zjpavt_client_nativemethod_JnIMethod
 * Method:    changeAllAirSwitchStatusNative
 * Signature: (ILjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zjpavt_client_nativemethod_JnIMethod_changeAllAirSwitchStatusNative
  (JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     com_zjpavt_client_nativemethod_JnIMethod
 * Method:    changeAirSwitchStatusNative
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zjpavt_client_nativemethod_JnIMethod_changeAirSwitchStatusNative
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_zjpavt_client_nativemethod_JnIMethod
 * Method:    changeChannelStatusNative
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zjpavt_client_nativemethod_JnIMethod_changeChannelStatusNative
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_zjpavt_client_nativemethod_JnIMethod
 * Method:    BuzzerNative
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zjpavt_client_nativemethod_JnIMethod_BuzzerNative
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_zjpavt_client_nativemethod_JnIMethod
 * Method:    ScanExuartNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_zjpavt_client_nativemethod_JnIMethod_ScanExuartNative
  (JNIEnv *, jclass);

/*
 * Class:     com_zjpavt_client_nativemethod_JnIMethod
 * Method:    getGpsTimeNative
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zjpavt_client_nativemethod_JnIMethod_getGpsTimeNative
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_zjpavt_client_nativemethod_JnIMethod
 * Method:    updateExtendDeviceInfoNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_zjpavt_client_nativemethod_JnIMethod_updateExtendDeviceInfoNative
  (JNIEnv *, jclass);

/*
 * Class:     com_zjpavt_client_nativemethod_JnIMethod
 * Method:    updateDoorStatusNative
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zjpavt_client_nativemethod_JnIMethod_updateDoorStatusNative
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_zjpavt_client_nativemethod_JnIMethod
 * Method:    sendDMX512SignalNative
 * Signature: ([BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zjpavt_client_nativemethod_JnIMethod_sendDMX512SignalNative
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_zjpavt_client_nativemethod_JnIMethod
 * Method:    restart4GNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zjpavt_client_nativemethod_JnIMethod_restart4GNative
  (JNIEnv *, jclass);

/*
 * Class:     com_zjpavt_client_nativemethod_JnIMethod
 * Method:    get4GSignalNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zjpavt_client_nativemethod_JnIMethod_get4GSignalNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
