/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestJni */

#ifndef _Included_TestJni
#define _Included_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestJni
 * Method:    print
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_TestJni_print
  (JNIEnv *, jobject, jstring);

/*
 * Class:     TestJni
 * Method:    printTextNative
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_TestJni_printTextNative
  (JNIEnv *, jclass, jstring);

/*
 * Class:     TestJni
 * Method:    printTextWithPosNative
 * Signature: (IIC)Z
 */
JNIEXPORT jboolean JNICALL Java_TestJni_printTextWithPosNative
  (JNIEnv *, jclass, jint, jint, jchar);

/*
 * Class:     TestJni
 * Method:    changeAllLedStatus
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_TestJni_changeAllLedStatus
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     TestJni
 * Method:    changeLedStatus
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_TestJni_changeLedStatus
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     TestJni
 * Method:    changeAllChannelStatus
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_TestJni_changeAllChannelStatus
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     TestJni
 * Method:    changeChannelStatus
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_TestJni_changeChannelStatus
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     TestJni
 * Method:    getChannelStatusNative
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_TestJni_getChannelStatusNative
  (JNIEnv *, jclass, jint);

/*
 * Class:     TestJni
 * Method:    getChannelNumNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_TestJni_getChannelNumNative
  (JNIEnv *, jclass);

/*
 * Class:     TestJni
 * Method:    getCircuitNative
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_TestJni_getCircuitNative
  (JNIEnv *, jclass, jint);

/*
 * Class:     TestJni
 * Method:    getGPSStatusNative
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_TestJni_getGPSStatusNative
  (JNIEnv *, jclass, jint);

/*
 * Class:     TestJni
 * Method:    getLightIntensityNative
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_TestJni_getLightIntensityNative
  (JNIEnv *, jclass, jint);

/*
 * Class:     TestJni
 * Method:    getCurrentAndVoltageNative
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_TestJni_getCurrentAndVoltageNative
  (JNIEnv *, jclass, jint);

/*
 * Class:     TestJni
 * Method:    getPowerNative
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_TestJni_getPowerNative
  (JNIEnv *, jclass, jint);

/*
 * Class:     TestJni
 * Method:    BuzzerNative
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_TestJni_BuzzerNative
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
